[package]
name = "rat-nexus"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
crossterm = "0.29.0"
ratatui = "0.29.0"
snafu = "0.8.9"
tokio = { version = "1.48.0", features = ["full"] }
